sudo: required
services:
  - docker

before_install:
  - docker build -t mnslarcher/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mnslarcher/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: docker-react
  env: docker-react-env
  bucket_name: elasticbeanstalk-eu-central-1-585981232603
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY